# -*- coding: utf-8 -*-
"""Seminar2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BYev84OOyKHRzyahJqtyq579_aKfy_g
"""

import numpy as np
import matplotlib.pyplot as plt
plt.rcParams ['font.family'] = 'tahoma'

# The Canvas environment cannot use input(), so we will set the value directly.
# (สภาพแวดล้อม Canvas ไม่สามารถใช้คำสั่ง input() ได้ ดังนั้นเราจะกำหนดค่าโดยตรง)
next_day = int(input("ป้อนวันที่ต้องการพยากรณ์ (8-31): ")) # วันที่ต้องการทำนาย

s = np.array([1248.78,
1244.48,
1236.61,
1250.09,
1248.03,
1251.26,
1262.67
]) # ดัชนีหุ้น
d = np.array([1,2,3,4,5,6,7]) # วันที่เก็บข้อมูล

# สร้างสมการพหุนาม (polynomial regression)
poly = np.poly1d(np.polyfit(d, s, 1))

# รับ input วันที่ต้องการทำนาย
# predict = poly(next_day)

# แสดงผล
print(f"สมการแนวโน้ม:\n{poly}")
predict = poly(next_day)
print(f"พยากรณ์หุ้นวันที่ {next_day} คือ {predict.round(2)} ")

# วาดกราฟ
plt.plot(d, s, 'o', label="ราคาหุ้นจริง")
plt.plot(d, poly(d), label=f"เส้นแนวโน้ม")
plt.scatter(next_day, predict, color="red", label="ค่าที่พยากรณ์")
plt.xlabel("วันที่")
plt.ylabel("ราคาหุ้น")
plt.legend()
plt.show()
